USE adlister_db;


CREATE TABLE users
(
id INT UNSIGNED AUTO_INCREMENT,
username VARCHAR (20) NOT NULL UNIQUE,
email VARCHAR (255) NOT NULL UNIQUE,
password VARCHAR (100) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE ads (
id INT UNSIGNED AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
title VARCHAR(100) NOT NULL,
description VARCHAR(500),
FOREIGN KEY (user_id) REFERENCES users (id),
PRIMARY KEY (id)
);